# Generated by Django 4.0 on 2022-09-18 08:39

from django.db import migrations, models
import scmapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0002_auto_20200404_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Book_ground',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=scmapp.models.filepath),
        ),
    ]
